# Generated by Django 2.2.5 on 2022-06-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220617_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typed_product', to='product.ProductType'),
        ),
    ]
