# Generated by Django 2.2.5 on 2022-06-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220625_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.CharField(help_text='Required', max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
